### ISSUE TITLE
（できたら）大会ロゴ設定してたら大会名を入力できないようにする 難しければフォームに「画像設定してない時は入力しないように」的な注意書き入れます

### ISSUE THREAD

**Issue by blacktails2** [blacktails2/BraceBracket#42]
![CleanShot 2022-05-28 at 10 46 50@2x](https://user-images.githubusercontent.com/6395616/170805191-4e9d026f-f9cf-42da-895e-287d6a2a16a7.png)

**Comment by tohutohu** [comment]
大会ロゴが設定され、ロゴの画像が1つ以上指定されている場合は大会名を表示しないようにしました
