### ISSUE TITLE
スコアの更新をブラウザ上から行えるようにする

### ISSUE THREAD

**Issue by tohutohu** [blacktails2/BraceBracket#9]
はじめまして。https://twitter.com/wolphtype/status/1526099157454589953 のツイートを見て、BraceBracketめちゃくちゃいいと思ったので少しでも協力できればと思いIssueを立てさせていただきます。
現状BraceBracketを利用するためには、ファイルをダウンロードしてくる必要があり、スコアを修正するためにはJSONファイルを直接編集する必要がありますが、これをブラウザだけで完結できるようにするのはどうでしょうか？
そうすればより使いやすくなるのではないかと思っての提案です。

僕の方でもコードを少しいじってプロトタイプを作ってみました。
https://tohutohu.github.io/BraceBracket/admin.html にアクセスして一番上の pass の入力欄に適当なパスフレーズを入力して「作成」ボタンを押すと、下にOBS用のURLが表示されます。
そのURLの内容と下のJSONの内容がsyncボタンを押すことによって同期されます。
![image](https://user-images.githubusercontent.com/19851537/168925295-e7a538e9-090b-4fc9-b07f-da4d755fd2c8.png)

メリットはこのページにアクセスすれば誰でも利用ができるようになることですが、デメリットとしてカスタマイズが現状ではできない（仕様を考えて実装すれば可能かも）という点があります。

JSONを直接編集するのではなく、ちゃんとUIを作ればより使いやすくもできるかなと考えています。
これ以外でもお手伝いできるところがあればさせていただきたいなと思っています。
よろしくお願いします。

**Comment by blacktails2** [comment]
初めまして！ご連絡ありがとうございます。
Webのみで特定のURLの発行・編集できるWebアプリのような形はBraceBracketの理想系でしたが、自分の技術力のなさから諦めていたところだったのでご提案いただけてとても嬉しいです。なのでぜひこの形でも開発したいと思います。
とはいえ現状のコードをダウンロードする形もカスタマイズがしやすい形として残し、両方で提供できたらと考えております。

簡単なスケッチですが、自分はこんな感じで実装できたらいいなと思っています。
<img width="1693" alt="CleanShot 2022-05-18 at 10 50 34@2x" src="https://user-images.githubusercontent.com/6395616/168940845-b2b84e9a-daa4-45fd-a5af-d2c324a4757b.png">

個人的に実装したいこととしては、

### 可能な限り実装したい
- レイアウトのカスタマイズ（Single, Dual, Solid、今後追加予定のSimple）
- ロゴ画像のアップロード
- 選手カメラ要素のオンオフ

### できるなら実装したい
- 共同編集
BraceBracketのウリがGoogleスプレッドシートを用いた共同編集なので、可能なら実装してみたいところです。Web上で実装が難しければ、GASで発行したURLを紐づけて、スプレッドシートで編集もできるようにするとかでしょうか…

- start.ggやchallongeとの連携
こちらは今ローカルの方で実装を進めていて、GraphQLで取得した配信台のチーム名や選手名を持ってくる、などができればいいなと考えています。

自分もUIデザインやスタイリングでは協力できると思いますので、進めていけたらと思います。
よろしくお願いいたします。

**Comment by tohutohu** [comment]
返信ありがとうございます！
僕がデザインがからっきしなのでうまく協力できればなと思います。

### 可能な限り実装したいについて
- レイアウトのカスタマイズ（Single, Dual, Solid、今後追加予定のSimple）
  - カスタマイズのイメージとしては上のスケッチにあるようなSingle, Dual, Solidなどのオプションの中からどれかを選ぶタイプのものでしょうか？それとも実際にHTMLやCSSをユーザーに書いてもらうことを想定しているでしょうか？
  前者は比較的簡単ですが、後者はWeb上だけで完結させるには少し考えることが多そうです。（手元に持ってきてもらって書いてもらうのが良さそう）
- ロゴ画像のアップロード
  - これは小さい画像（10MB以下）とかでいいならすぐに実装できそうです。
- 選手カメラ要素のオンオフ
  - カメラ要素の枠の表示・非表示だけであればすぐに実装できそうです。

### できるなら実装したいについて
- 共同編集
  - 実はすでに共同編集できるようになっています！adminの方を複数タブで開いて編集してsyncボタンを押すと、ほかのタブでもその編集が反映されるようになっています。
- start.ggやchallongeとの連携
  - できるとめちゃくちゃ便利そうですね！admin側の下にトーナメント表を表示して、クリックしたらスコアに反映するみたいなことができると使いやすそうです。

### その他
- 今後フロントエンドのフレームワーク（ReactやVue、jQueryなど）を導入する予定はありますか？OBS用の画面は無くても大丈夫ですが、admin側でstart.ggやchallongeとの連携などをちゃんと実装しようと思うと早いうちに導入した方がいいかもしれません。

上で提案していただいたスケッチをもとにもう少し修正してPull Requestを出そうかと思います。
よろしくお願いします。
